### ISSUE TITLE
CONTRIBUTING.md - npm install should be replaced with npm ci

### ISSUE THREAD

**Issue by dylvaz** [simple-icons/simple-icons-website#103]
As the title says, this will prevent contributors from writing to package-lock.json when installing dependencies and make the contributing experience just a tab bit better 😃.

Some info on npm ci:

    The new npm ci command installs from your lock-file ONLY. If your package.json and your lock-file are out of sync then it will report an error.

    It works by throwing away your node_modules and recreating it from scratch.

    Beyond guaranteeing you that you'll only get what is in your lock-file it's also much faster (2x-10x!) than npm install when you don't start with a node_modules.

**Comment by ericcornelissen** [comment]
Closing this as #104 is closed.

To be clear, I'd be more than happy to improve the developer experience and reduce the chances of accidentally updating `package-lock.json` to version 2. My proposal is to finish the discussion in #104 and open a new issue/Pull Request for a fix.
