### ISSUE TITLE
Removing color sorting

### ISSUE THREAD

**Issue by jorgeamadosoria** [simple-icons/simple-icons-website#107]
- [ ] Feature
- [ ] Bug
- [ ] Design
- [X] Other, namely: feature removal

### Description
Color sorting is a feature present in the website that provides very little value. 
Considerations: 
- It is a subjective sorting criteria that can't be applied in a deterministic way to an array of elements (such as the icons) due to colors being a multidimensional value.
- It offers little help to the user to find a particular icon or to search for related icons. The order in which colors are presented says nothing to the user.
- As sorting it has no purpose, since being at the beginning or the end of it means nothing for the icon: the relationship between colors can't be modeled in terms of one dimension.
- The existence of the feature forces the website to support it moving forward in any aspect the code needs to support. Example, the discussion here: #34 , where support for color sorting is required for non JS users. In this sense, a feature that is already merely (and subjectively) cosmetic is in practice requiring work to be maintained without offering much in the way of value to the user base.
- The removal of this feature would simplify the interface, reduce the weight of the HTML file by removing all --color-order
 attributes, and would remove the color-sorter dependency from the project.
- Not carrying this feature forward opens the possibility for different features to be added, like grouping by category or bulk downloading (#42). While these can be added without removing color sorting, it would be a better tradeoff to take one feature out and add another, at least regarding source code size.

If we can get consensus, I can remove this feature myself.

**Comment by ericcornelissen** [comment]
See also #38


---

**General statement**: I strongly disagree with this. First, I believe the aesthetic value of color sorting (even if imperfect) is important to those that value aesthetics. Moreover, I strongly believe that neither alphabetical ordering nor any other kind of ordering is any more useful than color ordering. No kind of ordering is useful, there are over 2000 icons now and going through them manually is simply not feasible. The only way useful to use the website is by searching, and once you search we have a useful ordering, namely by relevance to the search query. But, we must choice some kind of ordering when there's no search query.

Personally, I even think color sorting is superior to alphabetical ordering as color sorting discourages people from going through the list manually.

Lastly, just to be explicit about it, using random ordering for the sake of having no ordering makes no sense to me.

---

**Specific points**:

- The example of #34 seems a bit cherry-picked to me. Yes, some changes will require additional work to make it work for color sorting as well. However, #34 is more a concern with regards to user that have JS disabled than it has to do with color sorting.
- You're assuming that color sorting provides no value to the user base. This may be true, but you have no basis for making that claim so your point doesn't stand.
- Yes this could reduce the weight of the HTML, but so could removing alphabetical ordering.
- I don't see at all how not ordering by color helps with #42 or any kind of grouping. A selection of icons selected by a user is completely unrelated to the order in which icons are displayed on the page. As for grouping, there still has to be an ordering within the group, and that could still be by color.

---

With all that said, if there's consensus on removing it the by all means remove it :slightly_smiling_face:

**Comment by jorgeamadosoria** [comment]
> Yes this could reduce the weight of the HTML, but so could removing alphabetical ordering.

Yes, indeed. And if we could get rid of color sorting, I would propose alphabetical sorting next. I'm less adamant on removing alphabetical sorting however, since we do need to present the icons somehow to the user. might as well do it alphabetically. 
Still, I'm open to removing that. Ordering is not directly relevant to the functionality of this site, only search is. 

> You're assuming that color sorting provides no value to the user base...

It's true that since the website doesn't have readily available analytics (at least to me), I have no numbers to make a hard statement. I can change the statement to "I'm unable to imagine which purpose would it serve to color sort icons for an user". That's the sentiment anyways: I just don't see how this is useful.

> The example of Support both alphabetical and colored ordering for non-JS users #34 seems a bit cherry-picked...

It's the example I have at hand. If the website were to move in a different direction, like assigning hotkeys to not need a mouse, or add filters with secondary sorting, or add primary + secondary sorting, etc., then I would use those examples.
In any case, #34 shows the problem nicely: We need to support a demographic (non JS users) and that means all features for the website need to work for them, color sorting included. That's more work, for an unknown (imo, next to zero) amount of value provided.

> I don't see at all how not ordering by color helps...

It doesn't directly. However, removing features makes the project lighter, so adding future features have less impact. It "makes room" for new things. It's not really very important, but I like that removing a feature can help ease concerns when adding future ones.

> With all that said, if there's consensus on removing it the by all means remove it 🙂

I think our positions are clear. We would need more @simple-icons/maintainers to weigh in. Preferably all of them, since this is  a removal of a thing that exists and it may be a breaking change for the website.

**Comment by mondeja** [comment]
I strongly agree here with @ericcornelissen and want to give even more reasons:

- We can create color searching based in the implemented algorithm. This would be useful for color-brand comparisons and analysis. 
- Sorting by color is a very interesting visual feature, which prevents the page from becoming a simple search engine. This was even more clear in the old website version. If the argument against this is "to reduce website size", what would be the argument against the complete elimination of the whole style?

**Comment by ericcornelissen** [comment]
> It's true that since the website doesn't have readily available analytics (at least to me), I have no numbers to make a hard statement.

We don't have any analytics at the moment (beyond ad impressions, I guess).


> I can change the statement to "I'm unable to imagine which purpose would it serve to color sort icons for an user". That's the sentiment anyways: I just don't see how this is useful.

My point is exactly that I could use the same argument in favor of color sorting. I just don't see how alphabetical ordering is useful. But that's not an argument unless you have numbers, so there's no point in bringing it up.

> It doesn't directly. However, removing features makes the project lighter, so adding future features have less impact. It "makes room" for new things. It's not really very important, but I like that removing a feature can help ease concerns when adding future ones.

In that case this point adds nothing beyond a point that has preceded it. Both the point related to #34 and #42 are with regards to color sorting adding more complexity to the website which _could_(!!) make development of certain new features more difficult. Moreover, these points both presuppose that color sorting is useless and can (again) be applied equally well in the opposite direction if you believe alphabetical ordering is useless.

**Comment by jorgeamadosoria** [comment]
> In that case this point adds nothing beyond a point that has preceded it. Both the point related to #34 and #42 are with regards to color sorting adding more complexity to the website which _could_(!!) make development of certain new features more difficult. Moreover, these points both presuppose that color sorting is useless and can (again) be applied equally well in the opposite direction if you believe alphabetical ordering is useless.

Notice that the point is not simply that color sorting "adds more complexity", but rather, that it adds more complexity without offering an explicit return on that complexity.

For example, showing the color for each icon: explicit usefulness.
Search: arguably one of the most core of the features.
alphabetical sorting: barely useful.
color sorting: even less useful than alphabetical sorting, because it's not even a good fit or a deterministic order.

So, the idea is that color search does not justify the effort it requires by yielding a return in usefulness, while other features do.

And again, regarding alpha sorting: completely neutral on it. I don't care about it either way, and if someone else wants to remove it, I will go with the majority. Sorting in general, but color sorting in particular, is not something this kind of site needs. That's the overall point.

**Comment by mondeja** [comment]
> Notice that the point is not simply that color sorting "adds more complexity", but rather, that it adds more complexity without offering an explicit return on that complexity.

I've used that in the past looking for brands styling, so I can easily check those brands that share common color as their main to analyse what they are trying to express with it. In fact, what struck me the most about the project before I started contributing was this approach to brand color analysis, which was even more explicit with the greater approach to the color that the old design of the website had.

> So, the idea is that color search does not justify the effort it requires by yielding a return in usefulness

I find this assumption very subjective.

**Comment by service-paradis** [comment]
My vote goes to keep the color sorting option. @ericcornelissen and @mondeja already expressed most of my feelings toward the feature.
Most of the bullets in the original post are strongly opinionated. The others are not strong enough to justify its removal. If it becomes a pain to support this, we might revaluate its pertinence.

**Comment by jorgeamadosoria** [comment]
I'll close the ticket, then.
Just remember that I'm strongly in favor of removing everything related to color sorting as useless, if the issue ever comes up again.
