### ISSUE TITLE
Inconsistent Formatting in Header Links

### ISSUE THREAD

**Issue by adamrusted** [simple-icons/simple-icons-website#113]
### Kind of issue 
Design

### Description
Brand names in the header are inconsistently formatted. I would assume, given they're titles or brand names, that they should be capitalized as below, except when stylized a certain way:
- [x] Main Repository (currently 'main repository')
- [x] npm (correctly formatted, name is stylized lowecase)
- [x] Packagist (currently 'packagist')
- [x] jsDelivr (correctly formatted)
- [x] UNPKG (currently 'Unpkg')
- [x] Legal Disclaimer (currently 'Legal disclaimer')

**Comment by ericcornelissen** [comment]
I agree with all of your formattings @adamrusted, thanks for noticing!
