### ISSUE TITLE
Add (page for) first- and third-party packages/extensions

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#16]
**:information_source: If you're interested in this feature, please leave comment or add a :+1:**

---

### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

Add something to the website (a page, modal, other suggestions?) that lists the first-party packages/extensions ([npm package](https://www.npmjs.com/package/simple-icons), [packagist package](https://packagist.org/packages/simple-icons/simple-icons), [font](https://www.npmjs.com/package/simple-icons-font)) and [the (known) third-party packages/extensions](https://github.com/simple-icons/simple-icons#third-party-extensions).

See also https://github.com/simple-icons/simple-icons/issues/1382

**Comment by runxel** [comment]
Maybe just some links at the top, like in the Github Readme?
Everything else ist just not really discoverable, I think.

**Comment by ericcornelissen** [comment]
I'm mainly concerned that [the (known) third-party packages/extensions](https://github.com/simple-icons/simple-icons#third-party-extensions) won't fit 😅 I suppose [the simple-icons font](https://github.com/simple-icons/simple-icons-font) _could_ be added to the header though.


> Maybe just some links at the top, like in the Github Readme?

Do you mean a link to the GitHub README? If so, that is already there, it's the "About" link. Though that works, the idea behind this issue was (to discuss) to just integrate that into the website so it is "easier" to access.

**Comment by runxel** [comment]
> > Maybe just some links at the top, like in the Github Readme?
> 
> Do you mean a link to the GitHub README?


No no 😅
I just meant that these links should be very clearly visible, and not be hidden inside a modal or therelike.
Sorry for the confusion!

**Comment by jorgeamadosoria** [comment]
What's wrong with simply linking to the 3rd party table on Readme: https://github.com/simple-icons/simple-icons#third-party-extensions?

I think that's good enough.

**Comment by ericcornelissen** [comment]
There's nothing wrong with that - except for the fact that I'm personally of the opinion that would be confusing w.r.t. the existing link to the repo/readme.

This ticket is just for embedding that content in the website itself somehow, not hugely important but could potentially be useful. If you don't see value in this, feel free to close.

**Comment by jorgeamadosoria** [comment]
> There's nothing wrong with that - except for the fact that I'm personally of the opinion that would be confusing w.r.t. the existing link to the repo/readme.
> 
> This ticket is just for embedding that content in the website itself somehow, not hugely important but could potentially be useful. If you don't see value in this, feel free to close.

ok. Do you have a design in mind? This is not hard to code if a design is present, but the problem I'm having is visualizing how this would look.

Can you see how it would look like?

**Comment by ericcornelissen** [comment]
I would expect either a modal or a separate page with a button or link (respectively) on the main page.

Also, I would also expect that we should be able to extract the third-party extensions from the README of the main project. In fact, if we're going to copy the content in this repository I would be against implementing this.

**Comment by jorgeamadosoria** [comment]
> I would expect either a modal or a separate page with a button or link (respectively) on the main page.
> 
> Also, I would also expect that we should be able to extract the third-party extensions from the README of the main project. In fact, if we're going to copy the content in this repository I would be against implementing this.

Extract as in scrape the README?

**Comment by ericcornelissen** [comment]
Essentially yes, as it's markdown we could even try to just convert it to HTML that way. I'd be okay trying it out as we control the README anyway.

Alternatively, we could change the main project to store the third (and first?) party extensions in a (new) data file and have a script generate that part of its README e.g. every release ([similar to the `slugs.md` file](https://github.com/simple-icons/simple-icons/blob/d8bfda152b73cd4ddf0465288cb10477fb6ecc2f/.github/workflows/create-release.yml#L48-L49)). Then this project can use that data file to build a webpage.

**Comment by jorgeamadosoria** [comment]
> Essentially yes, as it's markdown we could even try to just convert it to HTML that way. I'd be okay trying it out as we control the README anyway.
> 
> Alternatively, we could change the main project to store the third (and first?) party extensions in a (new) data file and have a script generate that part of its README e.g. every release ([similar to the `slugs.md` file](https://github.com/simple-icons/simple-icons/blob/d8bfda152b73cd4ddf0465288cb10477fb6ecc2f/.github/workflows/create-release.yml#L48-L49)). Then this project can use that data file to build a webpage.

I'm ok with scraping first, and if it doesn't work or it's too burdensome, then we can go to the data file. A data file would be cleaner, but I really want to reduce infrastructure code (i.e., all the github related hooks and scripts, etc.) so scraping would be preferable if easy.
