### ISSUE TITLE
Website header links "GitHub" and "About" are nearly identical

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#27]
### Kind of issue 

- [x] Improvement
- [ ] Bug
- [ ] Other, namely:

### Description

Currently the _GitHub_ link on the website links to:

```
https://github.com/simple-icons/simple-icons
```

And the _About_ link on the website links to:

```
https://github.com/simple-icons/simple-icons#readme
```

The difference being:

```diff
- https://github.com/simple-icons/simple-icons
+ https://github.com/simple-icons/simple-icons#readme
```

I think it's worth considering removing one of the two. My suggestion would be to remove the _About_ link and possibly change the GitHub link to:

```
https://github.com/simple-icons/simple-icons#readme
```

Discussion and suggestions are welcome 🙂

**Comment by PeterShaggyNoble** [comment]
How about either linking directly to https://github.com/simple-icons/simple-icons/blob/develop/README.md instead or adding an "about" page to the site that pulls in the contents of the README?

**Comment by ericcornelissen** [comment]
For clarity https://github.com/simple-icons/simple-icons#readme links to the same page as https://github.com/simple-icons/simple-icons/blob/develop/README.md (including that, if the default branch changes from `develop` to something else, it still works).

Pulling in the README from [simple-icons/simple-icons](https://github.com/simple-icons/simple-icons) (which is already happinning [through the NPM dependency](https://github.com/simple-icons/simple-icons-website/blob/9a1116bb95d37d98db940e21805385a782e520f9/package.json#L28)) and somehow rendering it as HTML on the website is an interesting idea and would also address #16 :thinking: Not sure how feasible this is but definitely worth considering!
