### ISSUE TITLE
Alternative styling for brands with #FFFFFF as color

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#28]
### Kind of issue 

- [x] Improvement
- [ ] Bug
- [ ] Other, namely: 

### Description

Currently, the `.grid-item` of brands with an (almost) white brand color look a little bit off, e.g., as of writing this, [Zulip](https://simple-icons.github.io/simple-icons-website/?q=zulip):

| Non-white | White |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3742559/105087224-78052a80-5a9a-11eb-9611-7a19f3b2b9c7.png) | ![image](https://user-images.githubusercontent.com/3742559/105087151-599f2f00-5a9a-11eb-965a-37f436a3325a.png) |

Similarly, in dark mode brand with an (almost) black brand color look a little bit off:

| Non-black | Black |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3742559/105162203-9575db00-5b12-11eb-8c5e-00458ed1f61d.png) | ![image](https://user-images.githubusercontent.com/3742559/105162149-8727bf00-5b12-11eb-995f-140ae1d5f160.png) |

This could be improved, though I'm not sure how to change the styling :thinking:

**Comment by fbernhart** [comment]
The same way the visibility of dark colors could be improved while using the dark mode. E.g.:

![image](https://user-images.githubusercontent.com/70264417/105100229-48135280-5aad-11eb-986f-12b1aa0ba278.png)


How about adding a thin black frame (similar to the SVG and PDF buttons) around the color for the light theme?
And then a thin white frame for the dark theme?

**Comment by ericcornelissen** [comment]
> The same way the visibility of dark colors could be improved while using the dark mode. E.g.:
> 
> ![image](https://user-images.githubusercontent.com/70264417/105100229-48135280-5aad-11eb-986f-12b1aa0ba278.png)

Of course, good catch, I should have realized that 😆 I updated the original post 👍 


> How about adding a thin black frame (similar to the SVG and PDF buttons) around the color for the light theme? And then a thin white frame for the dark theme?

That _could_ work, but I'm not a fan of having that for all of the color buttons. We could definitely look into only adding a border to colors that are almost white or almost black 🤔

**Comment by ericcornelissen** [comment]
Resolved in c108923be9bb842dc0f67b31648ce56059af5164, thanks for the simple but surprisingly effective suggestion @fbernhart 😄
