### ISSUE TITLE
[Suggestion] Add support to download icons in a specified color

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#31]
**:information_source: If you're interested in this feature, please leave comment or add a :+1:**

---

### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely: 

### Description

Following an idea that appeared in [this redesign proposal](https://github.com/simple-icons/simple-icons/issues/980#issuecomment-547591284) add the option to download SVGs in a specific color, rather than no color/black.

**Comment by jorgeamadosoria** [comment]
I wouldn't add this in the current website.
Maybe if the icon detail view is ever implemented (#43), that would be a good place for this (and other) buttons

**Comment by jorgeamadosoria** [comment]
I've added this as a feature on #43. Can we close this one as a standalone ticket?

**Comment by jorgeamadosoria** [comment]
Given an apparent lack of interest in working on this feature, can we close it?
Personally, I don't think this is necessary. If someone needs the icon in a particular color, they can always edit the SVG manually or apply a CSS rule. There is no point in offering a feature for this. Brand color (which is a different ticket) should be enough.

------------------

After a brief discussion with @ericcornelissen, I'll be closing this ticket in a few days, unless any other @simple-icons/maintainers has a different opinion on the matter?
