### ISSUE TITLE
[Suggestion] Add support to download icons in the brand color

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#32]
**:information_source: If you're interested in this feature, please leave comment or add a :+1:**

---

### Kind of issue 

- [ ] Improvement
- [ ] Bug
- [x] Other, namely: _Feature_

### Description

Following an idea that appeared in [this redesign proposal](https://github.com/simple-icons/simple-icons/issues/980#issuecomment-547591284) add the option to download SVGs in a the brand color, rather than no color/black.

This would also (partially) address https://github.com/simple-icons/simple-icons/issues/1060.

**Comment by jorgeamadosoria** [comment]
I wouldn't add this in the current website.
Maybe if the icon detail view is ever implemented (#43), that would be a good place for this (and other) buttons

**Comment by jorgeamadosoria** [comment]
I'm going to close this one since I've added it as a feature of #43, where I think will make more sense.
