### ISSUE TITLE
Support "forced" color scheme for non-JS users

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#35]
### Kind of issue 

- [x] Improvement (when JS is disabled)
- [ ] Bug
- [ ] Other, namely:

### Description

Similar to #34, if JavaScript is disabled the user can only use the system default color scheme, whereas with JavaScript you can always choose dark mode or light mode. (forcefully overriding the system default).  We could support using a specific color scheme other than the system default for non-JS users by generating a versions of the website where each color scheme is the default and converting [the buttons to choose the color scheme](https://github.com/simple-icons/simple-icons-website/blob/42bab7dbdf3311eca8e0273d9532169ed2e9f454/public/index.pug#L70-L81) into links to the respective page for non-JS users.

I think we should support this, provided we can do so with minimum effort for keeping the two versions of the page in sync when [the .pug source](https://github.com/simple-icons/simple-icons-website/blob/42bab7dbdf3311eca8e0273d9532169ed2e9f454/public/index.pug) is changed. E.g. by somehow instructing the default color scheme in [the webpack configuration](https://github.com/simple-icons/simple-icons-website/blob/42bab7dbdf3311eca8e0273d9532169ed2e9f454/webpack.config.js), and than just generating both versions.

**Comment by jorgeamadosoria** [comment]
owing to previous discussions on the debatable relevance of color sorting and the apparent disinterest in working on this feature, can we close this issue? I don't foresee anyone working on this for at least the next few months, and the people affected is a tiny minority at best.

**Comment by jorgeamadosoria** [comment]
After a brief discussion with @ericcornelissen, I'll be closing this ticket in a few days, unless any other @simple-icons/maintainers has a different opinion on the matter?

**Comment by jorgeamadosoria** [comment]
Closed ticket due to lack of followup.
