### ISSUE TITLE
Improve website search

### ISSUE THREAD

**Issue by birjj** [simple-icons/simple-icons-website#36]
### Kind of issue 
  - [x] Improvement
  - [ ] Bug
  - [ ] Other, namely: 

### This issue concerns 
  - [ ] The NPM Package
  - [x] The website
  - [ ] Other, namely: 

### Description
Currently the website search performs poorly on some strings, not weighing exact matches high enough. For example, when you want to find Facebook by searching for "fa" it is preceded by the less accurate match "Fnac" (and several others):

![image](https://user-images.githubusercontent.com/4542461/53764235-fec3b500-3ecc-11e9-81a3-415e350e4c3c.png)

I have implemented a [somewhat better search algorithm here:](https://codepen.io/birjolaxew/pen/moEmXO)

<p align="center"><img width="33%" src="https://user-images.githubusercontent.com/4542461/53706621-6fb29080-3e2b-11e9-8696-67ab470fd630.png" /><img width="33%" src="https://user-images.githubusercontent.com/4542461/53706598-61647480-3e2b-11e9-831c-44c645025daa.png" /></p>

This search algorithm is based on the one described in [this blog post](https://www.forrestthewoods.com/blog/reverse_engineering_sublime_texts_fuzzy_match/), without some of the more fancy stuff. The bonuses/penalties for matching letters in specific positions have been tweaked based on our needs, putting more value on exact matches and on matches from the start of the string.

The big downside is that there is no easy way to filter out poor matches, because the score of each match depends on the length of the pattern and the length of the searched string. It could potentially be tweaked to better do this, but I don't have the time to do that right now.

Ideally we would implement this, or another search algorithm, on the website to give better search results.

**Comment by PeterShaggyNoble** [comment]
This does beg the question of whether "fuzzy matching" and sorting by relevance are even necessary. Chances are pretty high visitors are searching for _specific_ icons so should we instead return exact matches in alphabetical order?

**Comment by ericcornelissen** [comment]
I agree that bad matches can be a case against fuzzy matching and in favor of returning (something like) exact matches - I'm assuming you mean that the search query matches the start of the brand name - however, I do think it is very nice that [the query "fcebook"](https://simpleicons.org/?q=fcebook) gives me the icon of facebook. I would definitely be in favor of keeping "fuzzy matching" for that reason. Also, as a separate "data point", many code (and text?) editors have a functionality to search for and open a file based on its name, and though you (or at least I) typically know the name of the file it is nearly always implemented using fuzzy search. What do you think @PeterShaggyNoble?

I would expect we end up iterating over this issue a couple of times, but the above should be a good first step, I think.

**Comment by jorgeamadosoria** [comment]
> This does beg the question of whether "fuzzy matching" and sorting by relevance are even necessary. Chances are pretty high visitors are searching for _specific_ icons so should we instead return exact matches in alphabetical order?

sorting by relevance is definitely not necessary.
As a matter of fact sorting at all is not necessary. The icons should be presented sorted alphabetically and that's it, that's more than enough.

Regardless, I do think we should keep fuzzy search for the reasons @ericcornelissen explains.
