### ISSUE TITLE
Choose a default ordering

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#38]
**:information_source: If you're have an opinion regarding this discussion, please leave a :heart: if you prefer ordering by color and a :rocket: if you prefer ordering alphabetically. Also, feel free to leave a comment if you have more to add to the discussion**

---

### Kind of issue 

- [ ] Feature
- [ ] Bug
- [x] Design
- [ ] Other, namely:

### Description

This is a pretty simple discussion. For context: the original website always ordered the icons by color by default. The redesign currently orders the icons alphabetically by default. (In both versions, changing the ordering once will store that locally and restore that ordering when you revisit the page).

So the question is, which ordering should we use in the redesign. I see one obvious argument for either solution:

- Alphabetically: Makes logical sense, is probably more useful if you're looking for a specific brand.
- By color: Looks better, as the colors flow nicely throughout the page.

If you believe you have a good argument in favor of either, feel free to leave a comment (or add a :+1:  to a comment with that argument).

For those that don't want to try it out manually, here are two screenshots with a preview for both options (as of [v4.8.0 of simple-icons](https://github.com/simple-icons/simple-icons/tree/4.8.0)):

| Alphabetical ordering | Color ordering |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/3742559/105873829-2f9abf00-5ffc-11eb-8c3b-a5d29432120a.png) | ![image](https://user-images.githubusercontent.com/3742559/105873793-24e02a00-5ffc-11eb-977b-d5aafe984dae.png) |

**Comment by adamrusted** [comment]
I think ordering alphabetically, while not quite as pleasing as seeing the colours lined up, does allow easier viewing of the brands you're after. It also doesn't help that there are two _basically_ black hex codes at the start of the 'reds' in the colour ordering screenshot.

**Comment by ericcornelissen** [comment]
> I think ordering alphabetically, while not quite as pleasing as seeing the colours lined up, does allow easier viewing of the brands you're after.

It does indeed seems the majority is in favor of using alphabetical ordering, so I think we will switch to that with the redesign. After all, you only have to select order-by-color once to switch if you (like me) prefer that :slightly_smiling_face: 

I'm just leaving this open until we make the switch to the new website to allow for more people to voice their opinion.

> It also doesn't help that there are two basically black hex codes at the start of the 'reds' in the colour ordering screenshot.

That seems like a solvable issue. Currently the ordering is following exactly what [color-sorter](https://www.npmjs.com/package/color-sorter) gives us and we can either 1) improve that package, 2) look for another package, or 3) explicitly group blacks ourselves. This might be worth investigating so I'll open an issue for it, thanks for bringing it up :+1: EDIT: see https://github.com/simple-icons/simple-icons-website/issues/66

**Comment by ericcornelissen** [comment]
Without any further input I will be closing this without taking any further action. The website currently sorts alphabetically by default, which seems to be preferred by a majority.
