### ISSUE TITLE
[Suggestion] Display logos at a variaty of sizes

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#40]
**:information_source: If you're interested in this feature, please leave comment or add a :+1:**

---

### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

As per [this comment](https://github.com/simple-icons/simple-icons/issues/980#issuecomment-420645853):

> Add a way to see variant sizes of an icon (see e.g. how https://materialdesignicons.com/ handles it)

**Comment by jorgeamadosoria** [comment]
I think this can be covered in #43 and thus we can close it as a standalone ticket.
