### ISSUE TITLE
[Suggestion] Add indicator for "current letter" when ordering alphabetically

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#41]
**:information_source: If you're interested in this feature, please leave comment or add a :+1:**

---

### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

As per [this comment](https://github.com/simple-icons/simple-icons/issues/980#issuecomment-427140700), add an alphabetical indicator of where in the grid of icons you are - not present when ordering is by color or by relevance. For example. as seen in the mockup below :arrow_down: 

[An argument against this](https://github.com/simple-icons/simple-icons/issues/980#issuecomment-427157390) is that it is kind of redundant and may _compete_ with the search functionality (i.e. users may try to search manually by scrolling to the right first letter and looking for an icon manually).

![preview](https://user-images.githubusercontent.com/13542610/46497901-15a89300-c7d9-11e8-9550-79b4b117f8d7.png)

**Comment by jorgeamadosoria** [comment]
looks cool.

other than that it adds to the overall html and js size of the website, and it's only useful if the icons are alpha sorted (not sure if it should show on search results, since search results are significantly less in number and this may look bad in that case).

Too little usefulness for the HTML and js that needs to be added. I vote to close this one.

**Comment by ericcornelissen** [comment]
We could try a basic implementation to see if it looks bad when there are search results. Not to mention that it could just be hidden when there's a search query.

If size is a concern, this could still be added when we tackled that problem. In which case we could add a `pending` label for clarity.

**Comment by jorgeamadosoria** [comment]
size is always a concern with the way the icons are shown. The whole principle of serving the website as static HTML from the get go makes size a problem for... pretty much everything.

I would hide it on short search results. say, results <= 12 icons, so no scroll is needed.

again, I admit it looks very nice. But other than that... I'm going to focus more on the other tickets, for the time being.

**Comment by jorgeamadosoria** [comment]
Given a lack of interest in commenting or working on this issue, can we close it, @ericcornelissen ?

**Comment by ericcornelissen** [comment]
Up to you @jorgeamadosoria

**Comment by jorgeamadosoria** [comment]
> Up to you @jorgeamadosoria

I wouldn't want to close tickets I didn't open, even if I really want to.
