### ISSUE TITLE
[Suggestion] Download a collection of icons at once

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#42]
**:information_source: If you're interested in this feature, please leave comment or add a :+1:**

---

### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

As per [this comment](https://github.com/simple-icons/simple-icons/issues/980#issuecomment-547591284): add functionality to allow users to select an icon to be included a "collection", and then have the ability to download all the icons in the collection at once (probably as `.zip`). It could be nice to provide download options such as #31, #32, #33 for the collection (without it affecting anything else), similar to #43.

As per [this comment](https://github.com/simple-icons/simple-icons/issues/980#issuecomment-548487407) the benefits of this are not super clear, as it takes up space in the UI while most users probably only download a handful of icons when visiting the website...

**Comment by runxel** [comment]
Users are familiar with this kind of option (think Dropbox or Google Drive), but yes, most probably you don't actually do that, because if you need more than a handful you just use the Github zip download option, or a package.

I'm even wondering how big the dev cost would be for us (or are there ootb packages for that out there?).
Also: Zipping on the fly also is quite ressource intensive on the server, right?

**Comment by mondeja** [comment]
> I'm even wondering how big the dev cost would be for us (or are there ootb packages for that out there?).
> Also: Zipping on the fly also is quite ressource intensive on the server, right?

You can zipping on the fly client side, see for example [JSZip](https://stuk.github.io/jszip/).

**Comment by ericcornelissen** [comment]
> Users are familiar with this kind of option (think Dropbox or Google Drive), but yes, most probably you don't actually do that, because if you need more than a handful you just use the Github zip download option, or a package.

I don't think it is fair to assume users will know about the GitHub zip download option, and even so having to download everything if you just need 10 or 20 is unnecessary (and depending on your internet connect, very annoying). If we really think (or have evidence that) users that manually download many SVGs in one sitting, I think we should consider adding it. The priority of this feature may change depending on alternatives such as GitHub zip download, but do not in my opinion remove the need for us to support it.



> I'm even wondering how big the dev cost would be for us (or are there ootb packages for that out there?).

In my experience there are plenty of packages for various programming languages for creating `zip` files.

**Comment by runxel** [comment]
> You can zipping on the fly client side, see for example [JSZip](https://stuk.github.io/jszip/).

Oh wow, I stand corrected.
Would never have thought the client side could do this as well...

@ericcornelissen: I'm not against adding it! Quite the contrary. In my thoughts it just seemed more costly, dev time wise.

**Comment by jorgeamadosoria** [comment]
Speaking as an user, this is actually something I would like to see.
I usually add a few icons at a time, for example when making lists of social networks or programming languages. I also do this in other icon collections (i.e., Font Awesome) and I think a feature that would function as a cart of sorts, when one would search and store a few icons, and then download them all, that would be excellent.
Alternatively, downloading preset subsets of icons would also be an improvement.

**Comment by jorgeamadosoria** [comment]
After thinking about this for a bit, I see a problem with it, namely:
If the user needs to go through the icons clicking each one to add to a a cart for later download, that's more work than simply clicking for download directly, right? At least with a good connection.
So I don't know if there is really value in letting the user click on the cards to create a collection that is downloaded in a zip later on.

I still think that we could create preset collections to download (like programming languages, US companies, Airlines, etc.) although I understand that this is subjective and may be hard to decide where certain items can go.

Another thing that can be done is just provide a button for downloading a zip file with all visible icons, and let people search for a group of icons they would like to download.

The easiest thing would be to just download all icons in a zip file, zipped in the client or pre-zipped since it would contain all icons.

what does everyone thinks about this @simple-icons/maintainers ?

**Comment by sachinraja** [comment]
Could we perhaps have a quick download button for downloading a single icon without adding it to the cart?

**Comment by jorgeamadosoria** [comment]
> Could we perhaps have a quick download button for downloading a single icon without adding it to the cart?

we have that on each card already, the download button for each icon.
The idea here is to download several icons in one action.

**Comment by sachinraja** [comment]
I think allowing users to add to a collection of icons for download is still a nicer experience than individually downloading each one.

**Comment by jorgeamadosoria** [comment]
That's what I thought at first, too.
But what's the difference between the user clicking to add icons to a collection that they are going to download later, and the user simply downloading the icons? It seems like they need to click each icon to select it, and then click to download the collection.

I guess that you could argue that a collection that works as a cart in this way would give the user a chance to check the icons before downloading or something, but is that really that necessary, in a website that downloads icons for free?

I just don't see how the user is having a better time or experience doing this than just downloading the icons one by one like they need to do now.

**Comment by sachinraja** [comment]
I guess there isn't a good enough reason for collections then. I'm unable to think of why using a cart would be a better experience than individually downloading.

**Comment by jorgeamadosoria** [comment]
That's where I'm at now, as well.
I guess that we could contrive some cases. 

For example, a colection of icons that allow downloading by preset categories.

Another case could be favorite icons thay each user could keep in their local storage, but that doesn't really help a pot unless we allow for server side user preferences.

Or maybe the collection could allow user settings for download, like colored icons, pdf/svg/png per icon, I don't know.

Not really good choices, so I'm as out of ideas as you @sachinraja .

I guess I'm going to give this ticket another month to see if any @simple-icons/maintainers come up with something or express interest, and if not, I"ll close it and move on

**Comment by jorgeamadosoria** [comment]
Reading the original comment, they have an user case I hadn't considered, which is to build a svg sprite out of selected icons. 
I still don't think that justifies this feature dev investment, but it is a way to justify q cart like collection since it can't be done in any other way.

**Comment by jorgeamadosoria** [comment]
Unless interest is expressed in keeping this issue open, I think it can be closed as per the last few comments exchanged between @sachinraja and I. 

I fail to see a good reason to include the custom set download. 

Partial features for which this could be useful are: Preset collections and custom SVG sprites. If those are considered to be of interest (or are requested) then we can open specific issues for them separate from this, which is more general.

I'm marking this PR as abandoned and will be closing it in the first week of December, 2021, unless discussion happens or opposition is voiced

**Comment by jorgeamadosoria** [comment]
As per the previous comment, I'm closing this issue. It can always be reopened if someone requests a similar feature.
