### ISSUE TITLE
Support more query parameters

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#45]
**:information_source: If you're interested in this feature, please leave comment or add a :+1:**

---

### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

As per [this comment](https://github.com/simple-icons/simple-icons/discussions/4865#discussioncomment-352284) add more query parameters than just the one for the search parameter. E.g.:

- `?colorscheme=(dark|light|system)`: This loads the website with a specific color scheme. As the color scheme is also stored in [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) I don't think this should be added to the URL automatically. Instead it may be added to link new users to the website in a specific color scheme. For existing users - those with a preference stored - the color scheme in the URL should be ignored.
- `?ordering=(alpha|color|relevance)`: This loads the website with a specific ordering of the icons. As the ordering is also stored in [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) I don't think this should b added to the URL automatically. Instead, it may be added to link new users to the website with a specific ordering. FOr existing users - those with a preference stored - the ordering in the URL should be ignored.

**Comment by jorgeamadosoria** [comment]
Closed as per discussion on #132.
Basically, it's @ericcornelissen opinion (and mine) that the website does not really gain much by having this parameters, specially taking into consideration that users already have local preferences saved for the parameters mentioned.
