### ISSUE TITLE
[Discussion] Update controls design

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#46]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [x] Design
- [ ] Other, namely:

### Description

These are suggestions for changing the design of the controls.

- Move color mode buttons away from the other controls.
- Omit borders, e.g.:
  ![preview no brders](https://user-images.githubusercontent.com/3742559/107855545-44ac8600-6e23-11eb-84c3-9bdfa07e2876.png)
- As per [this comment](https://github.com/simple-icons/simple-icons/discussions/4865#discussioncomment-365975), grouped buttons, e.g.:
  ![preview grouped buttons](https://user-images.githubusercontent.com/3742559/107855622-d61bf800-6e23-11eb-891a-ef2340c74b3e.png)

**Comment by fbernhart** [comment]
I prefer the last version (grouped with borders). ☺️

**Comment by jorgeamadosoria** [comment]
grouped buttons with borders is fine by me. It hammers home the grouping and still provides clear separation of the actionable area against the background of the site.
