### ISSUE TITLE
Use consistent iconography

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#50]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [x] Design
- [ ] Other, namely:

### Description

Currently, the iconography is a bit inconsistent, the icons for ordering were custom made for the old website; the dark/light/system mode icons are taken from [Feather Icons] (the system one is custom-made based on Feather Icons icons); and for #47 we need a "legal" icon which Feather Icon's does not seem to have.

In the table below I aim to create an overview of some icon packs that I'm familiar with and whether or not they have each icon. The most obvious finding, it doesn't look like any icon pack provides "sort by color" or "sort by relevance" :sweat: 

| Icons | [Font Awesome] | [Feather Icons] | [iconsvg] | [Heroicons] | [Phosphor Icons] | [System UIcons] | [Material Design Icons]
| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Light mode | [Yes](https://fontawesome.com/icons/sun) | [Yes](https://feathericons.com/?query=sun) | Yes | Yes | Yes | No | Yes |
| Dark mode | [Yes](https://fontawesome.com/icons/moon) | [Yes](https://feathericons.com/?query=moon) | Yes | Yes | Yes | No | Yes |
| Light/Dark mode | No? | No? | No? | No? | No? | No | Yes |
| External link | [Yes](https://fontawesome.com/icons/external-link-alt) | [Yes](https://feathericons.com/?query=external-link) | Yes | Yes | Yes? | Yes? | Yes |
| Copy to clipboard | [Yes](https://fontawesome.com/icons/copy) | [Yes](https://feathericons.com/?query=copy) | Yes | Yes | Yes | Yes | Yes |
| Legal | [Yes](https://fontawesome.com/icons/balance-scale) | No | No | Yes | No | No | Yes |
| Sort alphabetically | [Yes](https://fontawesome.com/icons/sort-alpha-up) | No | No | No? | No? | No? | Yes |
| Sort by color | No? | No | No | No | No | No | Yes? |
| Sort by relevance | No? | No | No | No | No | No |  Yes? |

[Font Awesome]: https://fontawesome.com/
[Feather Icons]: https://feathericons.com/
[Heroicons]: https://heroicons.com/
[iconsvg]: https://iconsvg.xyz/
[Phosphor Icons]: https://phosphoricons.com/
[System UIcons]: https://systemuicons.com/
[Material Design Icons]: https://github.com/Templarian/MaterialDesign/

**Comment by fbernhart** [comment]
How about just sticking with custom made icons?

Assuming that we're all skilled enough to create SVG icons ourselves, we could as well create a custom legal/sort by color/etc. icon.

**Comment by ericcornelissen** [comment]
That works as well :+1:

**Comment by PeterShaggyNoble** [comment]
Can I throw [Material Design Icons](https://github.com/Templarian/MaterialDesign/) into the mix here as well?

## Themes
Light, dark & system

![Light mode](https://user-images.githubusercontent.com/15157491/109045176-2d935100-76cb-11eb-8e36-53cb65bd9805.png)![Dark mode](https://user-images.githubusercontent.com/15157491/109045262-456ad500-76cb-11eb-8132-bdaacdb9b143.png)![Light/Dark mode](https://user-images.githubusercontent.com/15157491/109045326-57e50e80-76cb-11eb-8257-1e6e0a6f735c.png)
## Legal
2 options

![Legal](https://user-images.githubusercontent.com/15157491/109045481-89f67080-76cb-11eb-9e37-1814a4409a5c.png)![Legal](https://user-images.githubusercontent.com/15157491/109045531-9aa6e680-76cb-11eb-8fa4-f36a0c6e6ecb.png)
## Sorting
Alpha, colour, colour or relevance & relevance

![Sort alphabetically](https://user-images.githubusercontent.com/15157491/109045683-c88c2b00-76cb-11eb-9ee2-585cddd087a3.png)![Sort by color](https://user-images.githubusercontent.com/15157491/109045884-07ba7c00-76cc-11eb-897c-b1bfb77c2519.png)![Sort by color / Sort by relevance](https://user-images.githubusercontent.com/15157491/109045982-2456b400-76cc-11eb-8ee7-bd6b339eee44.png)![Sort by relevance](https://user-images.githubusercontent.com/15157491/109046057-3b95a180-76cc-11eb-9990-7b50847a3f09.png)
## Copy
2 options each for copy & copied

![Copy](https://user-images.githubusercontent.com/15157491/109046175-5cf68d80-76cc-11eb-9227-4ab9fcd00235.png)![Copy](https://user-images.githubusercontent.com/15157491/109046305-7f88a680-76cc-11eb-9fe7-e7cbd70212e1.png)![Copied](https://user-images.githubusercontent.com/15157491/109151097-a80eb000-7761-11eb-9ec7-087f8168308c.png)![Copied](https://user-images.githubusercontent.com/15157491/109151180-bfe63400-7761-11eb-86b3-c1bb9773b8d9.png)
## Other
Link & download (if we needed it)

![External Link](https://user-images.githubusercontent.com/15157491/109045415-73501980-76cb-11eb-8946-52d25b6d36df.png)![Download](https://user-images.githubusercontent.com/15157491/109046708-f6be3a80-76cc-11eb-9f4b-1d351a1294e9.png)

**Comment by runxel** [comment]
There is also the new [Google Fonts icons](https://fonts.google.com/icons), which seems to be different to the Material icons... 🤔

**Comment by jorgeamadosoria** [comment]
Is this really that important? The icons looks fine, and is not as if we are sourcing them from their origins, we have the local svg code for each one.

Maybe since I don't have design experience I don't see something in the icons that looks bad to a more trained eye or something, but the site looks fine to me. 
Changing the icons is more work, so, does it really matter?

In case no @simple-icons/maintainers has a particular interest on this moving forward, I vote to close it in one or two weeks time from now. 
Plenty of other things to improve in the site still.

**Comment by jorgeamadosoria** [comment]
Due to be closed in 1 week's time unless @simple-icons/maintainers express interest in this moving forward.
