### ISSUE TITLE
Consider design for link to DISCLAIMER.md

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#58]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [x] Design
- [ ] Other, namely: _requirement_

### Description

~~Add a link to the `DISCLAIMER.md` of the project - depends on https://github.com/simple-icons/simple-icons/pull/4912.~~

In #74 we were not necessarily happy about the design aspect of the link to the disclaimer, but we merged it in in the interest of having some link while we figure out the design. This ticket now serves to keep this topic alive and potentially discuss the design of the link to the disclaimer.

**Comment by jorgeamadosoria** [comment]
This issue is included in the changes discussed in #39 .
I think we can close it and continue the discussion there.

**Comment by ericcornelissen** [comment]
Not sure if I agree. This issue exists because, at the time that #74 was merged, we thought that it would be better to put the disclaimer somewhere else. However, we thought this would require more work and considered this link to be of a high enough priority to be included immediately. #39 merely proposes to change the header links from text to icons. Even if we do decide to keep the disclaimer link in the header, what icon would we use for it in the context of #39? Or would we keep it as text?

**Comment by jorgeamadosoria** [comment]
there is a proposal in #39 for that. @PeterShaggyNoble uses a gavel for the disclaimer. Not a bad idea, maybe could be improved.
It could be an information icon for an about page with a dropdown that includes the disclaimer.
It could be many things, all of which will be by necessity discussed in #39.
We can keep the ticket open, but whatever gets decided in #39 will affect this one, to the point of closing it, even.

**Comment by ericcornelissen** [comment]
> there is a proposal in #39 for that. PeterShaggyNoble uses a gavel for the disclaimer. Not a bad idea, maybe could be improved.

I think I know which image you're referring to, but it's not in #39 nor in #74 (and I don't know where it is). While I don't disagree the gavel is a decent choice, I do wonder if it's clear enough for the disclaimer. To me, the link to the disclaimer should be very clear so that no one - whether you're looking for it or not - can misunderstand it. I think a gavel icon can easily be interpreted as being something else (e.g. a link to a license or terms of service).


> It could be many things, all of which will be by necessity discussed in #39.
> We can keep the ticket open, but whatever gets decided in #39 will affect this one, to the point of closing it, even.

I don't disagree with that, however it's not true the other way around - we could resolve this issue without resolve #39 by moving the disclaimer away from the header link (e.g. following one of the designs suggested in [this comment](https://github.com/simple-icons/simple-icons-website/pull/74#issuecomment-851030797), or your suggestion for an about page). This is why I think it deserves it's own ticket.


> It could be an information icon for an about page with a dropdown that includes the disclaimer.

That is an interesting suggestion, if we go this way I think we would need some more content to go with it though. But, if it's a separate page (or perhaps a modal?) I'm not sure why there needs to be a dropdown, it could just be a textual link.

Continuing the discussion of how we could redesign this, my current thought is to, combined with #49, update the footer and add the link there. This goes against [@PeterShaggyNoble's comment](https://github.com/simple-icons/simple-icons-website/pull/74#issuecomment-870393810) that "Given its importance, should we look into trying to position it somewhere near the search form so we can make it sticky?", but from my experience companies often add these kinds of links in the footer.

That said, I do very much understand that we kinda want everyone to see & read the disclaimer, which is unlikely if we put it in the footer. Having a button in the header to a page with the disclaimer, as you suggested @jorgeamadosoria, makes it more likely people will see it.

**Comment by jorgeamadosoria** [comment]
> 
> I think I know which image you're referring to, but it's not in #39 nor in #74 (and I don't know where it is). While I don't disagree the gavel is a decent choice, I do wonder if it's clear enough for the disclaimer. To me, the link to the disclaimer should be very clear so that no one - whether you're looking for it or not - can misunderstand it. I think a gavel icon can easily be interpreted as being something else (e.g. a link to a license or terms of service).

This is the page in question: https://petershaggynoble.github.io/SI-Sandbox/preview/
A gavel is a bit misleading, that's true, although I think it's better than nothing. I don't know what else could be used. Maybe an info button?

> I don't disagree with that, however it's not true the other way around - we could resolve this issue without resolve #39 by moving the disclaimer away from the header link (e.g. following one of the designs suggested in [this comment](https://github.com/simple-icons/simple-icons-website/pull/74#issuecomment-851030797), or your suggestion for an about page). This is why I think it deserves it's own ticket.

That is true. I'm convinced.

> That is an interesting suggestion, if we go this way I think we would need some more content to go with it though. But, if it's a separate page (or perhaps a modal?) I'm not sure why there needs to be a dropdown, it could just be a textual link.

I was thinking on a dropdown to put several things in there, not just the disclaimer, (in case more project info is required). If not, a modal could do just fine and no dropdown would be required.

> 
> Continuing the discussion of how we could redesign this, my current thought is to, combined with #49, update the footer and add the link there. This goes against [@PeterShaggyNoble's comment](https://github.com/simple-icons/simple-icons-website/pull/74#issuecomment-870393810) that "Given its importance, should we look into trying to position it somewhere near the search form so we can make it sticky?", but from my experience companies often add these kinds of links in the footer.

My problem with the footer is that the footer requires actual effort to be seen. Because the website loads all icons without pagination or anything, the footer by default is effectively hidden. It could be put there, but chances are it's not going to jump to anyone's attention. Having the Open Collective and Twitter links down there is not doing the project any favors, either. We should either make the footer sticky, or floating, or put it on the menu, or something of the sort.

> 
> That said, I do very much understand that we kinda want everyone to see & read the disclaimer, which is unlikely if we put it in the footer. Having a button in the header to a page with the disclaimer, as you suggested @jorgeamadosoria, makes it more likely people will see it.

Agreed on both accounts.



Should we start by converting the menu to icons as it is following @PeterShaggyNoble's menu design (and just discuss if there is a better alternative for the gavel)?
That could be a good starting point to later start adding more things to the menu, perhaps even the ones that are currently at the footer.

**Comment by ericcornelissen** [comment]
> This is the page in question: https://petershaggynoble.github.io/SI-Sandbox/preview/

Of course! Thanks for sharing


> A gavel is a bit misleading, that's true, although I think it's better than nothing. I don't know what else could be used. Maybe an info button?

I agree it's better than nothing in light of #39. I personally think the gavel is better than an info button, an info button could mean way more things than the gavel.


> I was thinking on a dropdown to put several things in there, not just the disclaimer, (in case more project info is required). If not, a modal could do just fine and no dropdown would be required.

Thanks for clarifying 👍 

> My problem with the footer is that the footer requires actual effort to be seen. Because the website loads all icons without pagination or anything, the footer by default is effectively hidden. It could be put there, but chances are it's not going to jump to anyone's attention. Having the Open Collective and Twitter links down there is not doing the project any favors, either. We should either make the footer sticky, or floating, or put it on the menu, or something of the sort.

That is indeed a fair criticism. Feel free to open an issue regarding the footer/Open Collective and Twitter links so we can keep the two discussion separate.


> Should we start by converting the menu to icons as it is following Peter's menu design (and just discuss if there is a better alternative for the gavel)?
> That could be a good starting point to later start adding more things to the menu, perhaps even the ones that are currently at the footer.

You can definitely start working on #39 first 👍
