### ISSUE TITLE
Add link to the Simple Icons Open Collective page

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#68]
### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

Add a link to the website that points to [the Simple Icons Open Collective page](https://opencollective.com/simple-icons).

**Comment by SUSHANT731** [comment]
Can you explain where exactly we have to add means the position ??

**Comment by ericcornelissen** [comment]
I was thinking to put it in [the header's list of external links](https://github.com/simple-icons/simple-icons-website/blob/913d7920e7de8b4ceb2013fe1326b08e87702438/public/index.pug#L34-L44), but if you have another suggestion feel free to share it :slightly_smiling_face:
