### ISSUE TITLE
Tabbing order confusion

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#86]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [ ] Design
- [x] Other, namely: a11y

### Description

Currently, tabbing through the website really only works if you're using the default ordering (alphabetical). If either colored ordering or relevance ordering (when searching) is used, tabbing through the grid items will result in jumping all over the page.

This is because the visual re-ordering of the grid items is achieved using the flexbox `order` property and dynamically assigned CSS variables. The idea behind this approach, when it was implemented, was to leverage the GPU to do the re-ordering.

Unfortunately, this is a minor (?) problem for accessibility and if performance isn't too bad when shuffling the elements around to preserve a sane tab ordering we should change the implementation.

**Comment by developStorm** [comment]
Can we switch between different [`tabindex`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) when changing ordering?

**Comment by ericcornelissen** [comment]
Thanks for the suggestion @developStorm, I excluded it originally because I always heard you _shouldn't_ set it to a value other than `-1` and `0` but now I agree that this seems like a decent use case. That said, I still think the first thing we should look into is just moving the DOM elements around.

**Comment by jorgeamadosoria** [comment]
> Thanks for the suggestion @developStorm, I excluded it originally because I always heard you _shouldn't_ set it to a value other than `-1` and `0` but now I agree that this seems like a decent use case. That said, I still think the first thing we should look into is just moving the DOM elements around.

moving DOM elements around will make #35 (EDIT: Meant #34) very hard.

**Comment by ericcornelissen** [comment]
Did you mean #34 @jorgeamadosoria?

**Comment by jorgeamadosoria** [comment]
> Did you mean #34 @jorgeamadosoria?

yes, #34

**Comment by ericcornelissen** [comment]
I'd say this issue definitely take precedence over #34, if you're concerned they will affect each other.

However, I'm not sure if I agree as I would tackle #34 (and #35 for that matter) at built time, but that can be discussed in the respective threads.
