### ISSUE TITLE
Add structured data

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#87]
### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

Add [structured data](https://developers.google.com/search/docs/guides/intro-structured-data) to the website. This could make the results in e.g. Google a bit nice when searching for "Simple Icons".

Any opinions on whether we should add this (@simple-icons/maintainers)?

**Comment by runxel** [comment]
I'm in favor of adding this. However my question is: What _kind_ of data shall we add? 🤔

**Comment by adamrusted** [comment]
So you could go as big/small as you like with it. I'd recommend saying we're an [Organization](https://schema.org/Organization), and using a similar structure to the below. Obviously we can remove Dan's attribution - but figured this would be a good nod to his original founding of the project. I've also added the maintainers to it, with our websites (if we have one) or GitHub profile otherwise. I think this JSON is the perfect place to reference people involved, and we can add stuff like 'funders', giving us the option to 'make available' the fact we're supported through Open Collective.

```html
<script type="application/ld+json">
{
	"@context": "http://schema.org",
	"@type": "Organization",
	"name": "Simple Icons",
	"description": "1965 Free SVG icons for popular brands",
	"logo": "https://simpleicons.org/icons/simpleicons.svg",
	"url": "https://simpleicons.org/",
	"founder": {
		"@type": "Person",
		"name": "Dan Leech",
		"url": "https://danleech.com/",
		"image": "https://avatars.githubusercontent.com/u/734706?v=4"
	},
	"members": [
		{
			"@type": "Person",
			"name": "Eric Cornellissen",
			"jobTitle": "Maintainer",
			"url": "https://ericcornelissen.dev/",
			"image": "https://avatars.githubusercontent.com/u/3742559?v=4"
		},
		{
			"@type": "Person",
			"name": "Álvaro Mondéjar",
			"jobTitle": "Maintainer",
			"url": "https://github.com/mondeja",
			"image": "https://avatars.githubusercontent.com/u/23049315?v=4"
		},
		{
			"@type": "Person",
			"name": "Lucas Becker",
			"jobTitle": "Maintainer",
			"url": "http://lucasbecker.de/",
			"image": "https://avatars.githubusercontent.com/u/2277182?v=4"
		},
		{
			"@type": "Person",
			"name": "Peter Noble",
			"jobTitle": "Maintainer",
			"url": "https://github.com/PeterShaggyNoble",
			"image": "https://avatars.githubusercontent.com/u/15157491?v=4"
		},
		{
			"@type": "Person",
			"name": "Florian Bernhart",
			"jobTitle": "Maintainer",
			"url": "https://github.com/fbernhart",
			"image": "https://avatars.githubusercontent.com/u/70264417?v=4"
		},
		{
			"@type": "Person",
			"name": "NovaGL",
			"jobTitle": "Maintainer",
			"url": "https://github.com/NovaGL",
			"image": "https://avatars.githubusercontent.com/u/16315601?v=4"
		},
		{
			"@type": "Person",
			"name": "Alexandre Paradis",
			"jobTitle": "Maintainer",
			"url": "https://alexandre-paradis.com/",
			"image": "https://avatars.githubusercontent.com/u/12817388?v=4"
		},
		{
			"@type": "Person",
			"name": "Adam Rusted",
			"jobTitle": "Maintainer",
			"url": "https://www.adamrusted.me/",
			"image": "https://avatars.githubusercontent.com/u/1830867?v=4"
		}
	]
}
</script>
```

**Comment by ericcornelissen** [comment]
Great start @adamrusted! Thanks for the initial work and I'd say feel free to open a Pull Request for it :smile: If you do so, I'd recommend trying to look into injecting the JSON through WebPack (similar to how, e.g., [the page title is inserted](https://github.com/simple-icons/simple-icons-website/blob/cc41ddcf3ce318611982daaabd8961da13f33a52/public/index.pug#L7)).

> Obviously we can remove Dan's attribution - but figured this would be a good nod to his original founding of the project.

I quite like it. But I'm open to removing it as well if other think that's better - after all he's not really associated with the project any more.

**Comment by ericcornelissen** [comment]
> I've also added the maintainers to it, with our websites (if we have one) or GitHub profile otherwise

Relatedly, we could add `<link rel="author" href="authors.txt">` to the header and an authors.txt file with a list of Simple Icons maintainers and contributors to the site. ([stole the idea from here](https://github.com/joshbuchea/HEAD#link), [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#attr-author)).

**Comment by jorgeamadosoria** [comment]
Testing with https://search.google.com/test/rich-results?url=https%3A%2F%2Fsimpleicons.org%2F&user_agent=1
the ads served by carbonads impide the page from getting further up in Google's page rank (or that's what I interpret from their results).

![image](https://user-images.githubusercontent.com/15719479/133910147-c3949d08-68d8-45c5-b504-0f648ff90058.png)

So the idea of adding the structured data is good, but without fixing that, I don't think it's going to matter a whole lot.
carbonads has a robot file that doesn't like bot crawling, hence the error.

**Comment by ericcornelissen** [comment]
I don't see the logic in not doing do this because it wouldn't improve our Google page rank by much. If it improves it by something, that by itself would be worth it. Not to mention that this could allow Google (and other search engines) to display "rich results" (i.e. more than just a link) for the website (admittedly, I'm not sure if any rich results will be displayed given [the latest proposed data](https://github.com/simple-icons/simple-icons-website/issues/87#issuecomment-873632286)), which I would say is valuable in and of itself (regardless of page rank).

Regarding the carbonads problem, I don't know if that reduces our ranking. If it does, I'm sure carbonads is aware of this problem and works to improve it. If you want to do something about that, rejecting this issue is not at all productive. You can start a discussion to change ad provider or remove ads altogether, but this is not the thread to discuss that.

**Comment by jorgeamadosoria** [comment]
> I don't see the logic in not doing do this because it wouldn't improve our Google page rank by much. If it improves it by something, that by itself would be worth it. Not to mention that this could allow Google (and other search engines) to display "rich results" (i.e. more than just a link) for the website (admittedly, I'm not sure if any rich results will be displayed given [the latest proposed data](https://github.com/simple-icons/simple-icons-website/issues/87#issuecomment-873632286)), which I would say is valuable in and of itself (regardless of page rank).
> 
> Regarding the carbonads problem, I don't know if that reduces our ranking. If it does, I'm sure carbonads is aware of this problem and works to improve it. If you want to do something about that, rejecting this issue is not at all productive. You can start a discussion to change ad provider or remove ads altogether, but this is not the thread to discuss that.

Haven't said anything about "not doing this" or "rejecting the issue". Raising a problem with the issue is not the same as rejecting it altogether.

**Comment by ericcornelissen** [comment]
> I don't think it's going to matter a whole lot.

This sounded like you thought this issue wasn't worth the effort. Apologies if I misunderstood.

The (potential) problem you raised seems out of scope for this issue to me.

**Comment by jorgeamadosoria** [comment]
> > I don't think it's going to matter a whole lot.
> 
> This sounded like you thought this issue wasn't worth the effort. Apologies if I misunderstood.
> 
> The (potential) problem you raised seems out of scope for this issue to me.

I meant that it may have to be addressed before continuing on with the definition of the data, that's all. I did say it is a good idea, I'm concerned about the effect being diminished if we don't do something about the current obstacles Google has flagged regarding carbonads, that's all.

**Comment by service-paradis** [comment]
I'm not 100% sure yet, but to solve the issue, I think we could just tell Google ourselves to ignore Carbon ads with our own `robots.txt` file.

**Comment by mondeja** [comment]
> Testing with https://search.google.com/test/rich-results?url=https%3A%2F%2Fsimpleicons.org%2F&user_agent=1 the ads served by carbonads impide the page from getting further up in Google's page rank (or that's what I interpret from their results).

I can't see this problem now. Maybe Google is ignoring carbonads nowadays 🤔 Could you check it again @jorgeamadosoria?

**Comment by jorgeamadosoria** [comment]
> > Testing with https://search.google.com/test/rich-results?url=https%3A%2F%2Fsimpleicons.org%2F&user_agent=1 the ads served by carbonads impide the page from getting further up in Google's page rank (or that's what I interpret from their results).
> 
> I can't see this problem now. Maybe Google is ignoring carbonads nowadays 🤔 Could you check it again @jorgeamadosoria?
> 

I don't see it either. Apparently Google changed something to our benefit for once. I'll take it.
