### ISSUE TITLE
Add instant search / search shortcut

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#88]
### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

We can make searching easier on the website by adding either of the following:

- Automatically start searching when the user starts typing (letters or numbers) anywhere on the website.
- Add a key/key combination to focus the search input. This _could_ be <kbd>Ctrl</kbd>+<kbd>f</kbd> but unless we support exact search I think we should keep support for browser search.

I personally like the former. Any opinions from others (@simple-icons/maintainers)?

**Comment by runxel** [comment]
I'm highly against highjacking of the built-in functions of browsers. Very disrespectful to the user imho.

I like the idea that the user can just type anywhere and it will search.
One more unobtrusive variant would be to search by typing "/" anywhere first – just like GitHub does.

**Comment by jorgeamadosoria** [comment]
owing to an apparent disinterest in this feature, can we close this ticket?
I personally think that it is neat, but really not necessary. It's a flourish that we can easily live without.
After a brief discussion with @ericcornelissen, I will close this ticket in a few days unless any other @simple-icons/maintainers has a different opinion.
