### ISSUE TITLE
Add a CSS reset

### ISSUE THREAD

**Issue by ericcornelissen** [simple-icons/simple-icons-website#89]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [ ] Design
- [x] Other, namely: refactor

### Description

We should consider adding a CSS reset (e.g. [Reset CSS](https://meyerweb.com/eric/tools/css/reset/) by _Eric A. Meyer_) to the website to improve consistency across browsers.

To anyone looking to work on this, please be sure to remove duplicated styles from existing CSS rules.

**Comment by priyansh32** [comment]
I would like to work on this issue.

**Comment by ericcornelissen** [comment]
That's great @priyansh32, I assigned you to this is - looking forward to your contribution
